/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/Cannon")]
    [LuaRegisterType(0x5854debe3b2e767c, typeof(LuaBehaviour))]
    public class Cannon : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "e437acb5cbc6e5d42b3cf629863ddb5b";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.ParticleSystem m_shotEffect = default;
        [SerializeField] public System.Double m_facingSpot = 0;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_shotEffect),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_facingSpot),
            };
        }
    }
}

#endif
