/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/CollectedNotification_UI")]
    [LuaRegisterType(0xc70666bdfd7b2d7a, typeof(LuaBehaviour))]
    public class CollectedNotification_UI : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "b339caafd9bea1a4e8922e1abc3a0632";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.Texture m_fishIcon = default;
        [SerializeField] public UnityEngine.Texture m_gemIcon = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_fishIcon),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_gemIcon),
                CreateSerializedProperty(_script.GetPropertyAt(2), null),
                CreateSerializedProperty(_script.GetPropertyAt(3), null),
            };
        }
    }
}

#endif
