/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/FishingSpotsModule")]
    [LuaRegisterType(0xf07cadff2ffbd486, typeof(LuaBehaviour))]
    public class FishingSpotsModule : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "35d80d62871f0b04283cbdd2ceb73862";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.GameObject m_collectedNotification = default;
        [SerializeField] public UnityEngine.GameObject m_fishPrefab = default;
        [SerializeField] public UnityEngine.GameObject m_treasurePrefab = default;
        [SerializeField] public System.Double m_treasureChance = 0;
        [SerializeField] public UnityEngine.Transform m_fishStorage = default;
        [LuaScriptPropertyAttribute("4a096131050877b47b58fd2a027bfea4")]
        [SerializeField] public UnityEngine.Object m_fishCaughtUI = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_collectedNotification),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_fishPrefab),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_treasurePrefab),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_treasureChance),
                CreateSerializedProperty(_script.GetPropertyAt(4), m_fishStorage),
                CreateSerializedProperty(_script.GetPropertyAt(5), m_fishCaughtUI),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/FishingSpotsModule/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
