/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/FishingSpotsModule")]
    [LuaRegisterType(0xf07cadff2ffbd486, typeof(LuaBehaviour))]
    public class FishingSpotsModule : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "35d80d62871f0b04283cbdd2ceb73862";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.GameObject m_fishPrefab = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_fishPrefab),
            };
        }
    }
}

#endif
