/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/GameManagerModule")]
    [LuaRegisterType(0xa6f96dec5676f24a, typeof(LuaBehaviour))]
    public class GameManagerModule : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "20f12ac26c5e01e4ca2203e1ca168d71";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public Highrise.AudioShader _mainMusic = default;
        [SerializeField] public System.Collections.Generic.List<UnityEngine.Texture> m_upgradesIcons = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), _mainMusic),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_upgradesIcons),
            };
        }
    }
}

#endif
