/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/PlayerControllerModule")]
    [LuaRegisterType(0x128f57ea093b8000, typeof(LuaBehaviour))]
    public class PlayerControllerModule : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "ba8c551ba245d904d9da06ee05e4a489";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.GameObject m_cannonBallPrefab = default;
        [SerializeField] public UnityEngine.GameObject m_stunnedEffectPrefab = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_cannonBallPrefab),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_stunnedEffectPrefab),
            };
        }
    }
}

#endif
