/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/Tentacle")]
    [LuaRegisterType(0xe633cce5d12830a3, typeof(LuaBehaviour))]
    public class Tentacle : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "fc94fe2cdeb934b42a6dc510dda67c43";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.Transform m_attackOrigin = default;
        [SerializeField] public System.Double m_attackRadius = 0;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_attackOrigin),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_attackRadius),
            };
        }
    }
}

#endif
