/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/Treasure")]
    [LuaRegisterType(0x38a63d74503aba44, typeof(LuaBehaviour))]
    public class Treasure : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "fb3ae033528640f44abd57263c28daf0";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.GameObject m_tapEffect = default;
        [SerializeField] public UnityEngine.GameObject m_collectedNotification = default;
        [SerializeField] public System.Double m_gemsContained = 0;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_tapEffect),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_collectedNotification),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_gemsContained),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/Treasure/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
