/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/TutorialModule")]
    [LuaRegisterType(0xb1451560b92d023b, typeof(LuaBehaviour))]
    public class TutorialModule : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "7902d563387287646be5a13673b0d1f1";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.GameObject m_arrowPrefab = default;
        [SerializeField] public UnityEngine.Transform m_cannonBallCratesParent = default;
        [SerializeField] public UnityEngine.Transform m_cannonsParent = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_arrowPrefab),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_cannonBallCratesParent),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_cannonsParent),
            };
        }
    }
}

#endif
