/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/UIManagerModule")]
    [LuaRegisterType(0xe3be2f8eee762c6, typeof(LuaBehaviour))]
    public class UIManagerModule : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "e08d7dd87b1906a488e6202662667873";
        public override string ScriptGUID => s_scriptGUID;

        [LuaScriptPropertyAttribute("3f16941e7d562b545a4b7294e8fcd2ac")]
        [SerializeField] public UnityEngine.Object m_hudUI = default;
        [LuaScriptPropertyAttribute("47f003f2293188042956abce3fa0e889")]
        [SerializeField] public UnityEngine.Object m_fishingUI = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_hudUI),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_fishingUI),
            };
        }
    }
}

#endif
