/*

    Copyright (c) 2025 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;
using Highrise.Studio;
using Highrise.Lua;
using UnityEditor;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/UIManagerModule")]
    [LuaRegisterType(0xe3be2f8eee762c6, typeof(LuaBehaviour))]
    public class UIManagerModule : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "e08d7dd87b1906a488e6202662667873";
        public override string ScriptGUID => s_scriptGUID;

        [LuaScriptPropertyAttribute("3f16941e7d562b545a4b7294e8fcd2ac")]
        [SerializeField] public UnityEngine.Object m_hudUI = default;
        [LuaScriptPropertyAttribute("47f003f2293188042956abce3fa0e889")]
        [SerializeField] public UnityEngine.Object m_fishingUI = default;
        [LuaScriptPropertyAttribute("a38c0e96fe00e2341923cb4dfbb970f4")]
        [SerializeField] public UnityEngine.Object m_upgradesUI = default;
        [LuaScriptPropertyAttribute("54b46ce87f5e60642ba89a1d2f477edb")]
        [SerializeField] public UnityEngine.Object m_rewardsUI = default;
        [LuaScriptPropertyAttribute("5048b09a707222d429a8533888707e1d")]
        [SerializeField] public UnityEngine.Object m_tutorialUI = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_hudUI),
                CreateSerializedProperty(_script.GetPropertyAt(1), m_fishingUI),
                CreateSerializedProperty(_script.GetPropertyAt(2), m_upgradesUI),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_rewardsUI),
                CreateSerializedProperty(_script.GetPropertyAt(4), m_tutorialUI),
            };
        }
        
#if HR_STUDIO
        [MenuItem("CONTEXT/UIManagerModule/Edit Script")]
        private static void EditScript()
        {
            VisualStudioCodeOpener.OpenPath(AssetDatabase.GUIDToAssetPath(s_scriptGUID));
        }
#endif
    }
}

#endif
